### PR TITLE
Persist dismissed machine config banner

### LINKED ISSUE #1393: Machine config banner doesn't fully dismiss
### Dev Home version

0.401.219.0

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Navigate to the machine configuration page
Close the banner
Restart Dev Home

### Expected result

The banner should remain dismissed and not pop back up. This works properly for the Dashboard banner.

### Actual result

The banner returns.

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by davidegiacometti**
## Summary of the pull request

- Persist dismissed machine config banner
- Aligned code that checks if banner should be showed in dashboard and rxtensions page

## References and relevant issues
https://github.com/microsoft/devhome/issues/1393

## Detailed description of the pull request / Additional comments

Verified that dismission of the banners in dashboard, machine config and extensions page is persisted when DevHome is restarted.

## PR checklist
- [x] Closes #1393
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Review by bbonaby — APPROVED** [review]

File: tools/SetupFlow/DevHome.SetupFlow/ViewModels/MainPageViewModel.cs [hunk 1]
```diff
@@ -29,6 +29,8 @@ namespace DevHome.SetupFlow.ViewModels;
 /// </summary>
 public partial class MainPageViewModel : SetupPageViewModelBase
 {
+    private const string _hideSetupFlowBannerKey = "HideSetupFLowBanner";
```
Comment (krschau) [inline tools/SetupFlow/DevHome.SetupFlow/ViewModels/MainPageViewModel.cs:32]: Tiny thing -- typo in capitalization
```suggestion
    private const string _hideSetupFlowBannerKey = "HideSetupFlowBanner";

```

**Review by krschau — CHANGES_REQUESTED** [review]

**Review by krschau — APPROVED** [review]
