### PR TITLE
Widgets: fix SSHWallet config path, remove CPU "End process" buttons, text size/weight

### LINKED ISSUE #1460: Align Dashboard and Widgets with design specs
### Provide a description of requested docs changes

Small changes need to be made to align with design specs.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/devhome/pull/1461
- [ ] https://github.com/microsoft/devhomegithubextension/pull/209
- [ ] https://github.com/microsoft/devhome/pull/1467
```

### PR DESCRIPTION
**Pull request by krschau**
## Summary of the pull request

Fix various widget issues:
- All widgets: text sizes and weights
- CPU Widget: remove "end process" buttons. They moved around too often to be useful, and the user can open task manager instead.
- SSH Wallet Widget: 
  - Style loading screen to properly center text
  - Fix issue where when a configuration file was submitted, the summary page would put the default location back into the TextBox rather than the current file. Instead fill with default path, or user specified path if available.

image

image

## PR checklist
- [ ] Closes #1460
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Review by guimafelipe — APPROVED** [review]

File: CoreWidgetProvider/Widgets/SSHWalletWidget.cs [hunk 1]
```diff
@@ -235,10 +235,11 @@ private JsonObject FillConfigurationData(bool hasConfiguration, string configFil
     {
         var configurationData = new JsonObject();
 
+        var defaultOrCurrentConfigFile = string.IsNullOrEmpty(configFile) ? DefaultConfigFile : configFile;
         var sshConfigData = new JsonObject
             {
                 { "configFile", configFile },
-                { "defaultConfigFile", DefaultConfigFile },
+                { "defaultOrCurrentConfigFile", defaultOrCurrentConfigFile },
```
Comment (dkbennett) [inline CoreWidgetProvider/Widgets/SSHWalletWidget.cs:242]: Not blocking, but this name seems awkward. Current config if one exists or default if it doesn't make sense, but the order here is reversed in the naming.

**Review by dkbennett — APPROVED** [review]
