### PR TITLE
[Environments] Extension Refresh & other fixes

### LINKED ISSUE #3112: [Environments reliability] Hyper-V Operations: Can't add standard user account to Hyper-V Administrator group if elevating using a separate administrator account
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22635.0

### Other software

_No response_

### Steps to reproduce the bug

* On my computer I have one standard user account and one administrator user account.
* When I run Dev Home as standard user and try to create an environment I get the message "The current user is not in the Hyper-V administrators group."
* I click the "Add user to group"-button, get a UAC prompt asking for an administrator account, I authenticate with my administrator account, the error message about "The current user is not in the Hyper-V administrators group." disappears.

### Expected result

My user is added to Hyper-V administrators group and I am able to create an environment.

### Actual result

When I once again try to create an environment I get the same message "The current user is not in the Hyper-V administrators group.".
When I start lusrmgr.msc and look in the Hyper-V Administrators group only my administrator account is added to it, probably because the PowerShell script adds my administrator account instead of my user account to Hyper-V Administrator group.

### Included System Information

_No response_

### Included Extensions Information

_No response_

### LINKED ISSUE #3219: Browse button when cloning to Environment browses local machine
### Dev Home version

0.1501.529.0

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Machine config > Set up an environment > Choose an environment (I chose Dev Box) > Add repository > Browse button for the path
image

### Expected result

We should probably not have a Browse button when cloning to an environment, unless we're able to browse the environment's folders

### Actual result

Clicking Browse opens my local File Explorer and allows me to choose a local folder path, which may not exist in the environment

### Included System Information

_No response_

### Included Extensions Information

_No response_

### LINKED ISSUE #3353: disabled all extensions but create environment shows dev box + hyper-v still
### Dev Home version

0.1501.547.0

### Windows build number

10.0.22631.3874

### Other software

OS Build Version: 10.0.22631.3874.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

1. nav to environment
2. click create
3. nav to extensions
4. disable everything
5. nav to environment
6. Click create
7. See hyper-v and dev box in that flow.

### Expected result

extensions are unloaded and creation flow is correctly handled without those extensions

### Actual result

image
image

### Included System Information

CPU: Intel(R) Core(TM) Ultra 7 165H
Physical Memory: 31.64GB (12.56GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1500.530.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1000.530.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1501.547.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18000.0.0_x64__cw5n1h2txyewy

### LINKED ISSUE #3568: [Machine Config] Dev Boxes not loading if multiple accounts logged in
### Dev Home version

0.1701.585.0

### Steps to reproduce the bug

Login with two accounts: One with Dev Boxes, and the other without any.
Got to Setup an Environment through Machine Configuration.

### Expected result

See Dev Boxes associated with the right account, and an error message for the account with no associated Dev Boxes

### Actual result

Only an error message is shown for the account with no associated Dev Boxes

### PR DESCRIPTION
**Pull request by huzaifa-d**
## Summary of the pull request
1. Bug fix - Fixes "Create Environments" button showing cached extension availability. 
Using the button after enabling extensions, didn't refresh the page and didn't show data from the enabled extension. 
The PR removes the caching code and refreshes the page every time navigated to.

2. Bug fix - Fixes adding incorrect user to Hyper - V admin group.
Adding a user to the Hyper-V admin group runs an elevated script. And getting the current user in this script returns the admin. 
The bug was that the admin was being added to the group, not the user who might have initiated the operation. The fix adds the user as a parameter to the script call.

3. Bug fix - Hides browse button under repo manager for remote machines.
Having a browse button, while configuring remote machines, was confusing as it browsed the local machine instead.
The PR hides the button in cases where remote machines are being configured.

4. Bug fix - Machine config page doesn't load extension data
If one of the accounts associated with an extension errored out, an exception caused the rest of the data to be skipped.
The PR removes the data with the errors from the relevant variable, since it has already been handled.

## Validation steps performed
Each fix was tested manually.

## PR checklist
- [ ] Closes #3353 
- [ ] Closes #3112 
- [ ] Closes #3219 
- [ ] Closes #3568

### CODE REVIEW

File: tools/SetupFlow/DevHome.SetupFlow/ViewModels/SetupFlowViewModel.cs [hunk 1]
```diff
@@ -149,8 +149,7 @@ public void OnNavigatedTo(NavigationEventArgs args)
         var parameter = args.Parameter?.ToString();
 
         if ((!string.IsNullOrEmpty(parameter)) &&
-            parameter.Contains(_creationFlowNavigationParameter, StringComparison.OrdinalIgnoreCase) &&
-            Orchestrator.CurrentSetupFlowKind != SetupFlowKind.CreateEnvironment)
```
Comment (huzaifa-d) [inline tools/SetupFlow/DevHome.SetupFlow/ViewModels/SetupFlowViewModel.cs:153]: This change was needed to make sure the Create Environment page is refreshed every time it is navigated to from the Environments page.

**Review by dhoehna — APPROVED** [review]

**Review by sshilov7 — APPROVED** [review]

File: tools/SetupFlow/DevHome.SetupFlow/ViewModels/SetupTargetViewModel.cs [hunk 2]
```diff
@@ -394,6 +395,14 @@ public async Task UpdateListViewModelList(ComputeSystemsLoadedData data)
     {
         _notificationsHelper?.DisplayComputeSystemEnumerationErrors(data);
 
+        // Remove the mappings that failed to load.
+        // The errors are already handled by the notification helper.
+        foreach (var mapping in data.DevIdToComputeSystemMap.Where(map =>
+            map.Value.Result.Status == ProviderOperationStatus.Failure))
```
Comment (sshilov7) [inline tools/SetupFlow/DevHome.SetupFlow/ViewModels/SetupTargetViewModel.cs:401]: nit: I think "kvp" is a more traditional name for a Key-Value pair variable. "map" sounds more like it's the whole dictionary not a KVP item from the dictionary.

Comment (huzaifa-d) [reply tools/SetupFlow/DevHome.SetupFlow/ViewModels/SetupTargetViewModel.cs]: Changed
