### PR TITLE
Fixed Clipboard Monitor text size and window width

### LINKED ISSUE #3693: Clipboard Monitor text is clipped when display text size > 100%
### Steps to reproduce the bug

I have my text size set to 140%. See results:
image

### LINKED ISSUE #3700: Clipboard Monitor window starts unnecessarily wide
### Steps to reproduce the bug

image

### Expected result

It should start the same width as the DI window.

### PR DESCRIPTION
**Pull request by andreww-msft**
## Summary of the pull request
Removed the unnecessary height restriction on the text, and set the window width to the same as the parent BarWindow width. The code was already in place to base the window size/position off the parent window, but the parent window wasn't getting set.

Closes #3693 
Closes #3700

### CODE REVIEW

**Review by zadesai — APPROVED** [review]

File: tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/Tool.cs [hunk 1]
```diff
@@ -71,6 +72,10 @@ public void Invoke()
         ToolLaunchOptions options = new();
         options.TargetProcessId = TargetAppData.Instance.TargetProcess?.Id;
         options.TargetHWnd = TargetAppData.Instance.HWnd;
+
+        var barWindow = Application.Current.GetService<PrimaryWindow>().DBarWindow;
+        options.ParentWindow = barWindow;
```
Comment (timkur) [inline tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/Tool.cs:77]: Does this mean that if the Bar window is closed, that the child window will be automatically closed too?

Comment (andreww-msft) [reply tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/Tool.cs:77]: That happens already; this doesn't make any difference to that behavior.

**Review by jaholme — APPROVED** [review]

**Review by timkur — APPROVED** [review]
:shipit:
