### PR TITLE
Detect renamed files and report commit log of original filename

### LINKED ISSUE #3576: [File Explorer] Git Renamed/moved files don't show status or latest commit
### Dev Home version

0.17 Dev

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

- (If needed) Enable experimental File Explorer
- (If needed) Register a cloned git repo, e.g., DevHome
- Rename a file, making sure git is aware of the rename. For example `git mv README.md README2.md`

### Expected result

I expect to see the renamed file show status and commit history.

### Actual result

I see empty fields in the Version Status, Last change date, and Last change message columns.

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by DefaultRyan**
## Detailed description of the pull request / Additional comments
First, we weren't parsing rename status properly, so the new filename was wrong. This caused file status lookups to miss the rename.

Second, renamed files were looking for the commit log for the renamed file, which hasn't been committed yet. So now we first check the current cached status to see if this file is renamed, and if so, use the old name to lookup the commit log.

Finally, added a unit test to validate the behavior.

While fixing up unit tests, also noticed we should fail more gracefully on files that don't have a commit history.

Also we should stop checking File.Attributes to skip folders, since we're no longer using the LibGit2Sharp API that didn't like folders, simplification is good, and I don't want to run the risk of accidentally hydrating anything in a virtualizing repo.

## Validation steps performed
Ran new unit test.
Built a private build and validated that the status and most recent commit appeared correct.

## PR checklist
- [ ] Closes #3576 
- [ ] Tests added/passed

### CODE REVIEW

File: extensions/GitExtension/FileExplorerGitIntegration/Models/RepositoryWrapper.cs [hunk 1]
```diff
@@ -171,6 +172,26 @@ public string GetFileStatus(string relativePath)
...
     }
 
+    private string GetOriginalPath(string relativePath)
+    {
+        _statusCache.Status.FileEntries.TryGetValue(relativePath, out var status);
+        if (status is null)
+        {
+            return relativePath;
+        }
+
```
Comment (ssparach) [inline extensions/GitExtension/FileExplorerGitIntegration/Models/RepositoryWrapper.cs:182]: nit: may we add a comment here stating that if a file is renamed the old name is used as the change has not been committed. Thanks!

File: extensions/GitExtension/FileExplorerGitIntegration.UnitTest/GitLocalRepositoryProviderUnitTests.cs [hunk 2]
```diff
@@ -94,12 +94,18 @@ public void GetProperties()
         GitLocalRepository repo = new GitLocalRepository(RepoPath);
         var result = repo.GetProperties(properties, relativePath);
         Assert.IsNotNull(result);
+
+        // Oddity: When sorting the full commit graph by time, the HEAD is a merge with two parents:
+        // 1. Third a/a1; f73b9567; Apr 7 15:31:13 2005 -0700
+        // 2. Fourth a/a1; d0114ab8; Apr 7 15:30:13 2005 -0700
+        // It would appear that commmit is older, but for some reason, this is the one that was found by LibGit2Sharp.
```
Comment (ssparach) [inline extensions/GitExtension/FileExplorerGitIntegration.UnitTest/GitLocalRepositoryProviderUnitTests.cs:101]: nit: typo

**Review by ssparach — APPROVED** [review]

File: extensions/GitExtension/FileExplorerGitIntegration/Models/RepositoryWrapper.cs [hunk 3]
```diff
@@ -171,6 +172,26 @@ public string GetFileStatus(string relativePath)
...
+        if (status.Status.HasFlag(FileStatus.RenamedInIndex))
+        {
+            return status.RenameOldPath ?? relativePath;
+        }
+        else if (status.Status.HasFlag(FileStatus.RenamedInWorkdir))
+        {
+            return status.RenameOldPath ?? relativePath;
+        }
```
Comment (dabhattimsft) [inline extensions/GitExtension/FileExplorerGitIntegration/Models/RepositoryWrapper.cs:192]: both conditions seems to be returning same thing. If that's intended, maybe combine in single if?

**Review by dabhattimsft — APPROVED** [review]
