### PR TITLE
Filter shown widgets to those from packages that also implement the Dev Home extension

### LINKED ISSUE #908: Custom widgets require a Microsoft package ID
### Dev Home version

Latest source (as of posting this)

### Steps to reproduce the bug

Create a custom widget and set a custom package id. Note that widget won't show.
Change the package ID to start with `Microsoft.Windows.DevHome` and the widget will show in the Add Widget dialog.

Issue is caused by the filter specified here:
"https://github.com/microsoft/devhome/blob/7d5f8c72bbf0eacef58239f415e8d3aa99e69628/tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs#L71

You can repro with the github extension by changing the package id here:
https://github.com/microsoft/devhomegithubextension/blob/af404f352650ba452f5c29e76226629ee6ae43aa/src/GithubPluginServer/Package.appxmanifest#L3

### PR DESCRIPTION
**Pull request by krschau**
## Summary of the pull request
We want to open up the widgets we show as available to the user, but we still want to limit the widgets to ones specifically meant to be shown in Dev Home. So instead of filtering on widget provider name, instead we will show widgets that _also_ implement the Dev Home extension.

We do this by finding all installed packages that implement `com.microsoft.windows.widgets' in the same way we find those that implement `com.microsoft.devhome`. In order to do this, we need to add com.microsoft.windows.widgets as a AppExtensionHost in the appxmanifest. Then we can take the intersection of the two lists, and a list of the PackageFamilyNames of that intersection.

We use the PackageFamilyName since that will match the first part of the Widget Provider's Id, so we can compare that Id to the list and know that the widget came from a package we want to include.

## PR checklist
- [x] Closes #908
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: src/Services/ExtensionService.cs [hunk 1]
```diff
@@ -204,6 +206,38 @@ public async Task<IEnumerable<IExtensionWrapper>> GetInstalledExtensionsAsync(bo
         }
     }
 
+    private async Task<IEnumerable<string>> GetInstalledWidgetExtensionsAsync()
+    {
+        await _getInstalledExtensionsLock.WaitAsync();
+        try
+        {
+            if (_installedWidgetsPackageFamilyNames.Count == 0)
```
Comment (EricJohnson327) [inline src/Services/ExtensionService.cs:214]: This is fine to unblock xbox, but you'll also want to implement events for loaded/unloaded/updated.  Otherwise widget extensions won't show up until Dev Home is restarted, or they may stick around for longer than they should if the extension is uninstalled.

**Review by EricJohnson327 — APPROVED** [review]

File: src/Services/ExtensionService.cs (hunk 1 above)
Comment (EricJohnson327) [reply src/Services/ExtensionService.cs:214]: We already do this for Dev Home extensions.  You should be able to follow the same model.

Comment (krschau) [reply src/Services/ExtensionService.cs:214]: I think the event handlers for Dev Home extensions actually cover widget extensions, at least as far as we care -- all three (installing, uninstalling, updating) essentially ask if the extension is (or was) a valid Dev Home extension. If it wasn't, ie. if it was just an app that has a widget associated with it (like Your Phone) then it was never in our list and we don't care about putting it in our list or removing it.

Comment (EricJohnson327) [reply src/Services/ExtensionService.cs:214]: Oh good call.  I didn't see you added it to OnPackageChange().  Looks good!

**Review by EricJohnson327 — APPROVED** [review]

File: tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs [hunk 2]
```diff
@@ -67,10 +70,18 @@ public static double GetPixelHeightFromWidgetSize(WidgetSize size)
...
+    public static async Task<bool> IsIncludedWidgetProviderAsync(WidgetProviderDefinition provider)
     {
-        var include = provider.Id.StartsWith("Microsoft.Windows.DevHome", StringComparison.CurrentCulture);
-        Log.Logger()?.ReportInfo("WidgetHelpers", $"Found provider Id = {provider.Id}, include = {include}");
+        var providerId = provider.Id;
+
+        var extensionService = Application.Current.GetService<IExtensionService>();
+        var enabledWidgetProviderIds = await extensionService.GetInstalledDevHomeWidgetPackageFamilyNamesAsync(true);
+
+        var endOfPfnIndex = providerId.IndexOf('!', StringComparison.Ordinal);
```
Comment (AmelBawa-msft) [inline tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs:80]: Is the `GetInstalledDevHomeWidgetPackageFamilyNamesAsync()` method the appropriate place for this task? As far as I know, package family names do not include `!`.

Reference: https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/package-identity-overview#package-full-name

**Review by AmelBawa-msft — APPROVED** [review]

File: src/Services/ExtensionService.cs [hunk 3]
```diff
@@ -204,6 +206,38 @@ public async Task<IEnumerable<IExtensionWrapper>> GetInstalledExtensionsAsync(bo
         }
     }
 
+    private async Task<IEnumerable<string>> GetInstalledWidgetExtensionsAsync()
```
[the remark this answers is not in the document]
Comment (krschau) [reply src/Services/ExtensionService.cs:209]: My thought here was why keep the entire ExtensionWrapper objects around when we only need one small piece? It also would mean doing extra work of getting a classId to create a proper ExtensionWrapper, or giving it junk data (string.Empty).

File: src/Services/ExtensionService.cs [hunk 4]
```diff
@@ -204,6 +206,38 @@ public async Task<IEnumerable<IExtensionWrapper>> GetInstalledExtensionsAsync(bo
         }
     }
 
+    private async Task<IEnumerable<string>> GetInstalledWidgetExtensionsAsync()
+    {
+        await _getInstalledExtensionsLock.WaitAsync();
```
[the remark this answers is not in the document]
Comment (krschau) [reply src/Services/ExtensionService.cs:211]: I originally gave it its own lock but the wait never ended, I thought maybe the catalog opening was tripping it up. I'll try again though, since I did make significant changes after that.

File: tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs (hunk 2 above)
Comment (krschau) [reply tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs:80]: Maybe the order this code is in is confusing... we are returning PackageFamilynames, but the ProviderDefinition's Id is PackageFamilyName!AppInfo.Id!!AppExtension.Id (the same as our ExtensionUniqueIds). That we have to trim down to compare to DevHome extensions' PFNs.

File: src/Services/ExtensionService.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (krschau) [reply src/Services/ExtensionService.cs]: Working now, gave this it's own lock.

File: tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs (hunk 2 above)
Comment (krschau) [reply tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs]: Reordered and added comments.

File: src/Services/ExtensionService.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (AmelBawa-msft) [reply src/Services/ExtensionService.cs:210]: Ohh my bad, you're right! I did not notice that in the other method the wrapper object was being created around the data.
