### PR TITLE
[Environments] Increased timeout for configuration

### LINKED ISSUE #3764: No longer able to filter environments via the textbox or the provider drop down in the environments page.
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

go to environments page when you have multiple environments available, and attempt to filter via the textbox or by the provider dropdown.

### Expected result

environments are filtered based on the user's selection. The only time no environments should appear is when the user types in an environment name that does not exist.

### Actual result

- if filtering via the provider dropdown, this works only once. Then subsequent times the filtering does not work and the previously filtered environments stay the same.
- When typing in the textbox, all environments are filtered out and no environments show up on the page.

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by huzaifa-d**
## Summary of the pull request
This PR
- Fixes filtering not working when no provider is selected.
- Increases the timeout for configuration tasks to align more closely with the actual timeouts needed.

## PR checklist
- [ ] Part of #3669 
- [ ] Closes #3764

### CODE REVIEW

File: tools/Environments/DevHome.Environments/ViewModels/LandingPageViewModel.cs [hunk 1]
```diff
@@ -409,10 +409,13 @@ public void SearchHandler(string query)
 
             if (system is ComputeSystemViewModel computeSystemViewModel)
             {
-                var providerName = computeSystemViewModel.ProviderDisplayName;
-                if (providerName != _selectedProvider)
+                if (_selectedProvider.ToString().Length > 0)
```
Comment (bbonaby) [inline tools/Environments/DevHome.Environments/ViewModels/LandingPageViewModel.cs:412]: Not blocking but since `_selectedProvider` is already a string we could do 

```C#
if (!string.IsNullOrEmpty(_selectedProvider))
{
    ....
}
```

or 

```C#
if (_selectedProvider.Length > 0)
{
    ....
}
```

Comment (bbonaby) [reply tools/Environments/DevHome.Environments/ViewModels/LandingPageViewModel.cs:412]: One question I do have though is whether this equality is also needed on line 402 in this file as well.

Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/ViewModels/LandingPageViewModel.cs]: Not needed in 402

File: tools/Environments/DevHome.Environments/ViewModels/LandingPageViewModel.cs [hunk 2]
```diff
@@ -409,10 +409,13 @@ public void SearchHandler(string query)
 
             if (system is ComputeSystemViewModel computeSystemViewModel)
             {
-                var providerName = computeSystemViewModel.ProviderDisplayName;
-                if (providerName != _selectedProvider)
+                if (_selectedProvider.Length > 0)
```
[the remark this answers is not in the document]
Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/ViewModels/LandingPageViewModel.cs]: _selectedProvider is never null, so I only want to check if it isn't empty. Will be keeping it as a preference.

**Review by bbonaby — APPROVED** [review]

**Review by sshilov7 — APPROVED** [review]
