### PR TITLE
Populate ComSafeWidgets after creation, handle failures

### LINKED ISSUE #2735: Able to pin multiple of widgets where AllowMultiple=false
### Dev Home version

0.13

### Steps to reproduce the bug

Pin a widget where AllowMultiple=false. Go to pin another widget -- the listing for the pinned widget is still enabled.

### Actual result

Bug introduced because the ComSafeWidgetObject isn't populated yet.

### PR DESCRIPTION
**Pull request by krschau**
## Summary of the pull request
Fixes issue where we were able to pin multiples of widgets where AllowMultiple = false, maybe other ones not yet found.
With lazy loading, ComSafeWidgets were only loaded with properties when a method was called on them. In the case that a property was called first, the ComSafeWidget didn't have its properties set, and would return the default (which, in the case of AllowMultiple, is true). We should call PopulateAsync() on all ComSafe* objects after new-ing them up. This was already done for ComSafeWidgetDefinitions.

## Validation steps performed
Validated locally.

## PR checklist
- [ ] Closes #2735
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: tools/Dashboard/DevHome.Dashboard/ComSafeWidgetObjects/ComSafeWidget.cs [hunk 1]
```diff
@@ -328,26 +339,21 @@ private async Task LazilyLoadOopWidget()
...
-                }
-                catch (Exception ex)
-                {
-                    Log.Warning(ex, $"Failed to operate on out-of-proc object with error code: 0x{ex.HResult:x}, try {retries} more times");
-                }
+                return widget.Id;
+            }
+            catch (Exception ex)
+            {
+                Log.Warning(ex, $"Failed to operate on out-of-proc object with error code: 0x{ex.HResult:x}");
```
Comment (dhoehna) [inline tools/Dashboard/DevHome.Dashboard/ComSafeWidgetObjects/ComSafeWidget.cs:356]: Is this exception coming from COM, or the OOP object?  If from the object, any exception is returned as a Generic Exception and the message will also be "Generic Exception"

**Review by dhoehna — APPROVED** [review]

File: tools/Dashboard/DevHome.Dashboard/ComSafeWidgetObjects/ComSafeWidget.cs (hunk 1 above)
Comment (krschau) [reply tools/Dashboard/DevHome.Dashboard/ComSafeWidgetObjects/ComSafeWidget.cs:356]: I'm specifically worried about COM, I don't _think_ we're expecting we can get any other exception here from the object.

**Review by EricJohnson327 — APPROVED** [review]
