### PR TITLE
Auto-refresh for Dev drive optimization and make trusted

### LINKED ISSUE #2595: Dev Drive Insights - after making a change to move a cache, the page is not refreshed with the changes
### Dev Home version

0.1201.466.0

### Windows build number

10.0.22631.3447

### Other software

_No response_

### Steps to reproduce the bug

I used insights to 'make the change' for my NPM package cache. After changing to D:\packages\npm-cache the page is not refreshed and the data is stale. 

I was able to get the data to refresh by navigating away from the Insights page and navigating back

### Expected result

It should say 'optimized'. Here's what it looks like after I navigated away and back:

image

### Actual result

It had the stale data

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by SohamDas2021**
## PR checklist
- [ ] Closes #2595
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: tools/Customization/DevHome.Customization/ViewModels/DevDriveInsightsViewModel.cs [hunk 1]
```diff
@@ -404,4 +412,20 @@ public void UpdateOptimizedListViewModelList()
 
         DevDriveOptimizedLoadingCompleted = true;
     }
+
+    /// <summary>
+    /// Implements the Receive method from the IRecipient<DevDriveOptimizedMessage> interface. When this message
+    /// is received we reload the UX.
```
Comment (krschau) [inline tools/Customization/DevHome.Customization/ViewModels/DevDriveInsightsViewModel.cs:418]:
```suggestion
    /// <summary>
    /// Implements the Receive method from the IRecipient<DevDriveOptimizedMessage> interface. When this message
    /// is received we reload the UX.
    /// </summary>
```

File: tools/Customization/DevHome.Customization/ViewModels/DevDriveInsightsViewModel.cs [hunk 2]
```diff
@@ -404,4 +412,20 @@ public void UpdateOptimizedListViewModelList()
...
+    /// Implements the Receive method from the IRecipient<DevDriveOptimizedMessage> interface. When this message
+    /// is received we reload the UX.
+    public void Receive(DevDriveOptimizedMessage message)
+    {
+        OnFirstNavigateTo();
+    }
+
+    /// <summary>
+    /// Implements the Receive method from the IRecipient<DevDriveTrustedMessage> interface. When this message
+    /// is received we reload the UX.
```
Comment (krschau) [inline tools/Customization/DevHome.Customization/ViewModels/DevDriveInsightsViewModel.cs:426]:
```suggestion
    /// <summary>
    /// Implements the Receive method from the IRecipient<DevDriveTrustedMessage> interface. When this message
    /// is received we reload the UX.
    /// </summary>
```

**Review by krschau — APPROVED** [review]

**Review by bbonaby — APPROVED** [review]
