### PR TITLE
Disable Hyper-V extension on ARM

### LINKED ISSUE #2783: Hyper-V features should be disabled in ARM devices
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Hyper-V features should be disabled in ARM devices

### Expected result

_No response_

### Actual result

Hyper-V features should be disabled in ARM devices

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by huzaifa-d**
## Summary of the pull request
Disable config and creation flow for Hyper-V extension on ARM.

## Validation steps performed
Tested on an ARM machine

## PR checklist
- [ ] Closes #2783 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: src/Services/ActivationService.cs [hunk 1]
```diff
@@ -85,6 +87,18 @@ private async Task StartupAsync()
...
         _themeSelectorService.ThemeChanged += (_, theme) => App.MainWindow.SetRequestedTheme(theme);
         _themeSelectorService.SetRequestedTheme();
+
+        // Disable Hyper-V extension on ARM on first run
+        if (!await _localSettingsService.ReadSettingAsync<bool>(WellKnownSettingsKeys.IsNotFirstRun))
+        {
+            var arch = RuntimeInformation.ProcessArchitecture;
+            if (arch == Architecture.Arm64 || arch == Architecture.Arm || arch == Architecture.Armv6)
+            {
+                await _localSettingsService.SaveSettingAsync<bool>(CommonConstants.HyperVUniqueId + "-ExtensionDisabled", true);
```
Comment (dkbennett) [inline src/Services/ActivationService.cs:97]: Why is this a setting, as opposed to some sort of "IsSupported" check elsewhere in the feature?

**Review by dkbennett — APPROVED** [review]
Approve, but have a design question that I don't think should block the PR.

File: src/Services/ActivationService.cs [hunk 2]
```diff
@@ -85,6 +87,18 @@ private async Task StartupAsync()
...
+                Log.Information("Disabling Hyper-V extension on ARM {Architecture}", arch);
```
Comment (krschau) [inline src/Services/ActivationService.cs:98]: nit
```suggestion
                Log.Information($"Disabling Hyper-V extension on ARM {arch}");
```

**Review by krschau — APPROVED** [review]

File: src/Services/ActivationService.cs [hunk 3]
```diff
@@ -85,6 +87,18 @@ private async Task StartupAsync()
         // Subscribe to theme changes.
         _themeSelectorService.ThemeChanged += (_, theme) => App.MainWindow.SetRequestedTheme(theme);
         _themeSelectorService.SetRequestedTheme();
+
+        // Disable Hyper-V extension on ARM on first run
+        if (!await _localSettingsService.ReadSettingAsync<bool>(WellKnownSettingsKeys.IsNotFirstRun))
+        {
+            var arch = RuntimeInformation.ProcessArchitecture;
```
Comment (sshilov7) [inline src/Services/ActivationService.cs:94]: Note: it may be possible to run x86 or x64 DevHome on [ARM64EC](https://learn.microsoft.com/en-us/windows/arm/arm64ec) devices. We don't install those architectures, but users could force it or architectures we build can change in the future. It would be more correct to check device architecture instead of running process architecture.

Comment (huzaifa-d) [reply src/Services/ActivationService.cs]: Changed

File: src/Services/ActivationService.cs (hunk 1 above)
Comment (huzaifa-d) [reply src/Services/ActivationService.cs]: Changed the implementation completely.

File: extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs [hunk 4]
```diff
@@ -95,46 +96,58 @@ public ComputeSystemOperations SupportedOperations
...
-            // for the VM.
-            return ComputeSystemOperations.ApplyConfiguration;
+            // Disable ApplyConfiguration for ARM
+            var arch = RuntimeInformation.ProcessArchitecture;
+            if (arch == Architecture.Arm64 || arch == Architecture.Arm || arch == Architecture.Armv6)
+            {
+                supportedOperations &= ~ComputeSystemOperations.ApplyConfiguration;
+            }
+
+            return supportedOperations;
```
Comment (bbonaby) [inline extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs:150]: Would it be simpler to just remove the `ComputeSystemOperations.ApplyConfiguration` from the switch statements and then add it at the end in line 150? This way you  can just do `return supportedOperations` so something like this:

```Suggestion
            var supportedOperations = ComputeSystemOperations.None;
            var revertOperation = Guid.Empty.Equals(ParentCheckpointId) ? ComputeSystemOperations.None : ComputeSystemOperations.RevertSnapshot;

            switch (GetState())
            {
                case ComputeSystemState.Running:
                    // Supported operations when running
                    supportedOperations = ComputeSystemOperations.ShutDown |
                        ComputeSystemOperations.Terminate |
                        ComputeSystemOperations.Save |
                        ComputeSystemOperations.Pause |
                        ComputeSystemOperations.CreateSnapshot |
                        ComputeSystemOperations.Restart |
                        revertOperation;
                    break;
                case ComputeSystemState.Stopped:
                    // Supported operations when stopped
                    supportedOperations = ComputeSystemOperations.Start |
                        ComputeSystemOperations.CreateSnapshot |
                        ComputeSystemOperations.Delete;
                    break;
                case ComputeSystemState.Saved:
                    // Supported operations when saved
                    supportedOperations = ComputeSystemOperations.Start |
                        ComputeSystemOperations.CreateSnapshot |
                        ComputeSystemOperations.Delete |
                        revertOperation;
                    break;
                case ComputeSystemState.Paused:
                    // Supported operations when paused
                    supportedOperations = ComputeSystemOperations.Terminate |
                        ComputeSystemOperations.Save |
                        ComputeSystemOperations.Resume |
                        ComputeSystemOperations.CreateSnapshot |
                        revertOperation;
                    break;
            }

            // Disable ApplyConfiguration for ARM
            var arch = RuntimeInformation.ProcessArchitecture;
            if (arch == Architecture.Arm64 || arch == Architecture.Arm || arch == Architecture.Armv6)
            {
                return supportedOperations;
            }

            return supportedOperations | ComputeSystemOperations.ApplyConfiguration;
```

File: extensions/HyperVExtension/src/HyperVExtension/Providers/HyperVProvider.cs [hunk 5]
```diff
@@ -64,7 +65,22 @@ public class HyperVProvider : IComputeSystemProvider
...
 
     /// <summary> Gets the supported operations of the Hyper-V provider. </summary>
-    public ComputeSystemProviderOperations SupportedOperations => ComputeSystemProviderOperations.CreateComputeSystem;
+    public ComputeSystemProviderOperations SupportedOperations
+    {
+        get
+        {
+            // Disable the create operation for ARM devices.
+            var arch = RuntimeInformation.OSArchitecture;
+            if (arch == Architecture.Arm64 || arch == Architecture.Arm || arch == Architecture.Armv6)
```
Comment (sshilov7) [inline extensions/HyperVExtension/src/HyperVExtension/Providers/HyperVProvider.cs:74]: Coding guidelines: "Use parentheses to make clauses in an expression apparent."

**Review by sshilov7 — APPROVED** [review]
