### PR TITLE
fix environment deletion dialog to respect theme changes

### LINKED ISSUE #3753: The delete environment dialog does not respect Dev Homes theme
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

- Change your Dev Home's theme to be the opposite of your current Windows theme. E.g if current Windows theme is in Dark theme change Dev Home's theme to Light theme.
- Have any environment created that supports deletion e.g Hyper-V, WSL or Dev Box.
- Navigate to the environments page and click the three horizontal dots in the card.
- click the delete option
- Notice that the dialog is using the Windows theme still and not Dev Homes theme.

### Expected result

The delete environment dialog respects Dev Home's theme.

### Actual result

The delete environment dialog only uses the current Windows theme. 
See accessibility bug: https://task.ms/52460592

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by bbonaby**
## Summary of the pull request
fixes accessibility issue where we weren't respecting the app's theme when launching the "Delete environment" dialog. To do this, we'll now use Dev Homes theme service to get the current theme of the app, and use that as the requested theme for the dialog. 

**Before:**

https://github.com/user-attachments/assets/842a0768-607b-4526-9047-499c82159f29

**After**

https://github.com/user-attachments/assets/2016c01c-d35b-4b80-9bb7-a0b83365a22e

## PR checklist
- [x] Closes #3753
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs [hunk 1]
```diff
@@ -142,18 +144,20 @@ public void InvokeAction()
...
         if (ComputeSystemOperation == ComputeSystemOperations.Delete)
         {
-            ContentDialog noWifiDialog = new ContentDialog
+            var themeService = Application.Current.GetService<IThemeSelectorService>();
+            var deletionContentDialog = new ContentDialog
             {
                 Title = _stringResource.GetLocalized("DeleteEnviroment_Title"),
                 Content = _stringResource.GetLocalized("DeleteEnviroment_Content"),
                 PrimaryButtonText = _stringResource.GetLocalized("DeleteEnviroment_ConfirmButton"),
                 SecondaryButtonText = _stringResource.GetLocalized("DeleteEnviroment_CancelButton"),
```
Comment (krschau) [inline tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:153]:
```suggestion
                Title = _stringResource.GetLocalized("DeleteEnvironment_Title"),
                Content = _stringResource.GetLocalized("DeleteEnvironment_Content"),
                PrimaryButtonText = _stringResource.GetLocalized("DeleteEnvironment_ConfirmButton"),
                SecondaryButtonText = _stringResource.GetLocalized("DeleteEnvironment_CancelButton"),
```

**Review by krschau — APPROVED** [review]

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs (hunk 1 above)
Comment (bbonaby) [reply tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs]: updated, thanks

**Review by kanismohammed — APPROVED** [review]
