### PR TITLE
Really fix Dashboard crash when widgets runtime isn't present 

### LINKED ISSUE #3816: DevHome crashes on startup: GetWidgetPlatformRuntimePackage returns null
### Steps to reproduce the bug

In WidgetServiceService.GetWidgetPlatformRuntimePackage, packages.Count is zero, which seems to be unexpected.

### PR DESCRIPTION
**Pull request by krschau**
## Summary of the pull request
#3819 wasn't a sufficient fix because we were still calling .First() on a potentially empty list. Instead, check if there's anything in the list and return null if there isn't.

## PR checklist
- [ ] Closes #3816
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Review by guimafelipe — APPROVED** [review]

File: tools/Dashboard/DevHome.Dashboard/Services/WidgetServiceService.cs [hunk 1]
```diff
@@ -79,15 +79,26 @@ private Package GetWebExperiencePackPackage()
...
         var minSupportedVersion = new Version(1, 0, 0, 0);
 
         var packages = _packageDeploymentService.FindPackagesForCurrentUser(WidgetHelpers.WidgetsPlatformRuntimePackageFamilyName, (minSupportedVersion, null));
-        return packages.First();
+        if (packages.Any())
+        {
+            return packages.First();
+        }
+
+        return null;
```
Comment (bbonaby) [inline tools/Dashboard/DevHome.Dashboard/Services/WidgetServiceService.cs:101]:
```Suggestion C#
        return packages.FirstOrDefault();
```

**Review by bbonaby — APPROVED** [review]
