### PR TITLE
Consolidating hashing code.

### LINKED ISSUE #488: Remove duplicate DeveloperID hashing code
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

To minimize platform code changes for DevHome I duplicated the DeveloperId hashing code instead of moving it to a helper location.

This bug is to track the work to de-dupe.

### Expected result

_No response_

### Actual result

_No response_

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by dhoehna**
## Summary of the pull request
In a hurry to add telemetry to Dev Home I copy/pasted developer ID hashing code.

This PR is to put the logic in one place.

## References and relevant issues
#488 

## Validation steps performed
Ran the setup flow that fired events required a developer ID.

## PR checklist
- [ X] Closes #488 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Review by krschau — APPROVED** [review]

File: common/TelemetryEvents/DeveloperIdHelper.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+namespace DevHome.Common.TelemetryEvents;
+public static class DeveloperIdHelper
+{
+    public static string GetHashedDeveloperId(string providerName, IDeveloperId devId)
+    {
+        // TODO: Instead of LoginId, hash a globally unique id of DeveloperId (like url)
+        // https://github.com/microsoft/devhome/issues/611
+        using var hasher = SHA256.Create();
+        var loginIdBytes = Encoding.ASCII.GetBytes(devId.LoginId());
+        var hashedLoginId = hasher.ComputeHash(loginIdBytes);
```
Comment (dkbennett) [inline common/TelemetryEvents/DeveloperIdHelper.cs:18]: Not blocking feedback, but would it be a little more readable the hash were truncated? We dont actually need the hash to be matchable to anything, just a quasi-unique identifier obfuscating the real developer id, right? In that case IMO it would be nice to shorten it since a sha 256 hash can be quite a long string.
