### PR TITLE
DevDiagnostics - Move the enablement of local watson collection to a separate process

### LINKED ISSUE #3695: Local WER collection toggle vs Change button is confusing
### Steps to reproduce the bug

In normal (ie, non-admin) usage, the Local WER collection toggle is disabled. The Change button is enabled. It's not clear to me what is the purpose of the Change button. Even though it's enabled, clicking it does nothing. I see the tooltip telling me I can't change the setting unless running as admin - which to me explains why the Local WER toggle is disabled - but it doesn't explain what the Change button does, why it's enabled/inoperative, and why the tooltip is on this button instead of the toggle.

image

### PR DESCRIPTION
**Pull request by timkur**
## Summary of the pull request

The original implementation to enable local WER collection for an app involved having to relaunch DevDiagnostics elevated. This lead to some clumsy UX...

image

This cleans up the UX a bit, and to enable/disable local WER collection, will launch a separate app that will require a UAC.

image

It's not perfect yet, and definitely looking to Design to help clean this up further.

## Detailed description of the pull request / Additional comments

To help facilitate some code sharing between the standalone exe and DevDiagnostics, I ended up creating a shared WERUtils.cs that was used to read/enable/disable local cab collection.

## Validation steps performed

Enabled/disabled WER collection. Confirmed Narrator works for the updates (I end up having Narrator read the tooltip for the button when the user selects it).

## PR checklist
- [ ] Closes #3695 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/WERUtils.cs [hunk 1]
```diff
@@ -0,0 +1,118 @@
+﻿// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+
+using System.Diagnostics;
+using Microsoft.Win32;
+
+namespace DevHome.DevDiagnostics.Helpers;
+
+internal sealed class WERUtils
```
Comment (andreww-msft) [inline tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/WERUtils.cs:9]: No exception handling in this class, nor in its caller...?

Comment (timkur) [reply tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/WERUtils.cs:9]: No, if it fails, something bad has happened... not much we can do to recover.

Comment (andreww-msft) [reply tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/WERUtils.cs:9]: Right, but log before we failfast?

Comment (timkur) [reply tools/DevDiagnostics/DevHome.DevDiagnostics/Helpers/WERUtils.cs:9]: I'm not sure where/what I would log. If I'm unable to read the registry, the exception will bubble up to either DevDiagnostics or EnableLocalCabCollection and result in a Watson crash.

Same goes with the writing.... it would fail if this is called from a medium IL context, but should work elevated. If I'm wrong, there will be a Watson crash to track the failure.

**Review by andreww-msft — APPROVED** [review]

File: tools/DevDiagnostics/DevHome.DevDiagnostics/ViewModels/WERPageViewModel.cs [hunk 2]
```diff
@@ -199,55 +213,66 @@ public void ResetBucketingTool()
...
+                    UseShellExecute = true,
+                    WorkingDirectory = fileInfo.DirectoryName,
+                    Verb = "runas",
+                };
+
+                var process = Process.Start(startInfo);
+                if (process is not null)
+                {
+                    // Wait for the process to update registry keys
+                    process.WaitForExit();
```
Comment (jaholme) [inline tools/DevDiagnostics/DevHome.DevDiagnostics/ViewModels/WERPageViewModel.cs:261]: there is no way to tell if the separate exe was successful.  At a minimum I would hope we could use the process exit code.

Comment (timkur) [reply tools/DevDiagnostics/DevHome.DevDiagnostics/ViewModels/WERPageViewModel.cs:263]: Just pushed an update that compares the "enabled" status before and after the launch, and it they are the same (meaning we were unsuccessful in toggling the setting) we'll log a telemetry point.

I'm hoping if this is unsuccessful, we'll see it in a Watson crash from the helper exe.

**Review by jaholme — APPROVED** [review]
:shipit:
