### PR TITLE
Hyper-V extension: Check guest OS version before apply configuration.

### LINKED ISSUE #3664: [Environments reliability] Hyper-V Configuration error: The parameter is incorrect. (0x80070057)
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Attempt to configure a Win 10/11 Hyper-V VM

### Expected result

User is able to configure their Win 10/11 VM. If it succeeds, re-attempt to configure the VM again.

### Actual result

The user receives an error similar to:

"Cannot send message to VM '<VM guid>': 'Failed to set value of the item '<DevSetup-Id>' Data Exchange integration service item for virtual machine '<VM Name>': The parameter is incorrect. (0x80070057) "

I can repro this one, I noticed when I get this error message, if I restart the VM and try again it'll work once before I get the error again. I'll add the logs to this issue once I have them. 

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by sshilov7**
## Summary of the pull request
This change adds a check for the guest OS platform and version in "apply configuration" operation for a Hyper-V VM. If VM is not a Windows VM 19041+ the operation will be aborted with "This operation is not supported for the guest OS" message.

We should disable configure environment operation in UI for VMs that don't support it. The work will be in a separate change. (This implementation of getting guest OS version requires the VM to be running, not good for UX where VMs are in a not running state)

Fix an off-by-one bug that was causing #3664.
 
## References and relevant issues
#3662
#3663
#3664

## Validation steps performed
Tested with Windows and Ubuntu OS's.

## PR checklist
- [ ] Closes #3664
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+            GuestOsProperties.TryGetValue(HyperVStrings.OSVersion, out var osVersion);
+            GuestOsProperties.TryGetValue(HyperVStrings.OSName, out var osName);
+            if ((osPlatformId != null) ||
+                (osVersion != null) ||
+                (osName != null))
+            {
+                message.Append(" (");
+                if (osPlatformId != null)
+                {
+                    message.Append(CultureInfo.InvariantCulture, $"{HyperVStrings.OSPlatformId} = {osPlatformId}");
```
Comment (bbonaby) [inline extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs:50]: Should we do Append or AppendLine here? Only really matters when we're viewing the logs/telemetry so I could go either way.

File: extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+        {
+            message.Append(CultureInfo.InvariantCulture, $" {InnerException}.");
+        }
+
+        if (GuestOsProperties != null)
+        {
+            GuestOsProperties.TryGetValue(HyperVStrings.OSPlatformId, out var osPlatformId);
+            GuestOsProperties.TryGetValue(HyperVStrings.OSVersion, out var osVersion);
+            GuestOsProperties.TryGetValue(HyperVStrings.OSName, out var osName);
+            if ((osPlatformId != null) ||
```
Comment (bbonaby) [inline extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs:43]: Not blocking but I feel like maybe it would be good reporting info for us to know if one was null or not in the strings below. As in, should we capture this null info in the strings instead of keeping them behind the null checks?

File: extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs [hunk 3]
```diff
@@ -806,6 +810,48 @@ public SDK.ApplyConfigurationResult ApplyConfiguration(ApplyConfigurationOperati
...
+    private void ThrowIfApplyConfigurationIsNotSupported(GuestKvpSession guestSession)
+    {
+        Dictionary<string, string>? osVersionInfo = null;
+        var isApplyConfigurationSupported = false;
+
+        try
+        {
+            osVersionInfo = GetOsVersionInfo(guestSession);
+            var osPlatformId = int.Parse(osVersionInfo[HyperVStrings.OSPlatformId], CultureInfo.InvariantCulture);
+            if (osPlatformId == Constants.GuestPlatformIdWindows)
```
Comment (bbonaby) [inline extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs:822]: Would we ever be worried about Case sensitivity? This has been around for so long where they probably will never change these, but figured I'd ask

File: extensions/HyperVExtension/src/HyperVExtension/Strings/en-US/Resources.resw [hunk 4]
```diff
@@ -201,6 +201,18 @@
...
+  <data name="FailedToReadGuestOsProperties" xml:space="preserve">
+    <value>Failed to read guest OS properties</value>
+    <comment>Error text to tell the user that an error happened while trying to read virtual machine's OS properties.</comment>
+  </data>
+  <data name="FailedToDetermineGuestOsVersion" xml:space="preserve">
+    <value>Failed to determine guest OS version</value>
+    <comment>Error text to tell the user that an error happened while trying to determine virtual machine's OS version.</comment>
+  </data>
+  <data name="GuestOsOperationNotSupported" xml:space="preserve">
+    <value>This operation is not supported for the guest OS</value>
```
Comment (bbonaby) [inline extensions/HyperVExtension/src/HyperVExtension/Strings/en-US/Resources.resw:213]: Should we say which version we support in the error text as well? And the one above it

File: extensions/HyperVExtension/src/HyperVExtension/Constants.cs [hunk 5]
```diff
@@ -28,4 +28,8 @@ internal sealed class Constants
     public const string HyperVTemplatesSubPath = @"HyperVExtension\Templates";
 
     public static string SystemRootPath { get; } = Path.GetPathRoot(Environment.SystemDirectory)!;
+
+    public static int GuestPlatformIdWindows { get; } = (int)Windows.Win32.System.Diagnostics.Debug.VER_PLATFORM.VER_PLATFORM_WIN32_NT;
```
Comment (bbonaby) [inline extensions/HyperVExtension/src/HyperVExtension/Constants.cs:32]: For `Windows.Win32.System.Diagnostics`, should we put this in a using statement?

File: extensions/HyperVExtension/src/HyperVExtension/CommunicationWithGuest/GuestKvpChannel.cs [hunk 6]
```diff
@@ -237,17 +237,17 @@ private List<IResponseMessage> TryReadResponseMessages(string communicationId, b
...
-    private Dictionary<string, string> ReadRawGuestKvps()
+    private Dictionary<string, string> ReadRawGuestKvps(string itemsType)
     {
         Dictionary<string, string> guestKvps = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
 
         using var collection = _vmWmi.GetRelated("Msvm_KvpExchangeComponent");
         foreach (ManagementObject kvpExchangeComponent in collection)
         {
-            foreach (var exchangeDataItem in (string[])kvpExchangeComponent["GuestExchangeItems"])
+            foreach (var exchangeDataItem in (string[])kvpExchangeComponent[itemsType])
```
Comment (bbonaby) [inline extensions/HyperVExtension/src/HyperVExtension/CommunicationWithGuest/GuestKvpChannel.cs:250]: Do you think it would ever be likely that the `kvpExchangeComponent` doesn't contain the `itemsType` causing it to throw? 

I guess answering my own question, if it does throw that's still fine as we wouldn't want to continue the configuration if we can't figure out the OS details of the VM correct?

File: extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs (hunk 1 above)
Comment (sshilov7) [reply extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs:50]: I didn't want to add new lines for simplicity if we want to search in logs, telemetry, etc. It's in parenthesis as additional data, so I think that's good enough.

File: extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs (hunk 2 above)
Comment (sshilov7) [reply extensions/HyperVExtension/src/HyperVExtension/Exceptions/GuestOsVersionException.cs:43]: I thought about that and decided not to output "null", "no data", or whatever so users don't get the impression that it a mistake in the code. The fact that one of them is not in the output means it was null.

File: extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs (hunk 3 above)
Comment (sshilov7) [reply extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs:822]: Not sure. I'll change it to be on the safe side.

File: extensions/HyperVExtension/src/HyperVExtension/Strings/en-US/Resources.resw (hunk 4 above)
Comment (sshilov7) [reply extensions/HyperVExtension/src/HyperVExtension/Strings/en-US/Resources.resw:213]: I planned it to be a generic message for other situations, but yes, I can add something like "The operation requires {0}."

File: extensions/HyperVExtension/src/HyperVExtension/Constants.cs (hunk 5 above)
Comment (sshilov7) [reply extensions/HyperVExtension/src/HyperVExtension/Constants.cs:32]: Was one time thing. I'll add it for "Windows.Win32.System.Diagnostics.Debug"

File: extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs (hunk 3 above)
Comment (sshilov7) [reply extensions/HyperVExtension/src/HyperVExtension/Models/HyperVVirtualMachine.cs:822]: Actually, the dictionary returned from GetOsVersionInfo->ReadGuestProperties is StringComparer.OrdinalIgnoreCase.
I'll add a comment.

File: extensions/HyperVExtension/src/HyperVExtension/CommunicationWithGuest/GuestKvpChannel.cs (hunk 6 above)
Comment (sshilov7) [reply extensions/HyperVExtension/src/HyperVExtension/CommunicationWithGuest/GuestKvpChannel.cs:250]: Yes, if it will throw that would mean we can't continue. Most likely KVP service is not supported or in a non-functional state.

**Review by bbonaby — APPROVED** [review]

**Review by bbonaby — APPROVED** [review]

**Review by huzaifa-d — APPROVED** [review]

**Review by huzaifa-d — APPROVED** [review]

**Review by bbonaby — APPROVED** [review]
