### PR TITLE
Unsubscribe from OnExtensionsChanged when unloading Extensions page

### LINKED ISSUE #3859: Crash in Extensions page (formerly "Quickstart playground crash")
### Dev Home version

0.1801.621.0

### Windows build number

10.0.22631.4169

### Other software

OS Build Version: 10.0.22631.4169.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

1. go to machine config
2. click quickstart playground without a key
3. click cancel
4. click combo box in upper right
5. click cancel 

it crashed, unable to repro however

### Expected result

Calling out: Kristen referenced oddity on stacktrace from event viewer as I was on quickstart playground but trace shows extension page

### Actual result
```
Application: DevHome.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80004005): Unspecified error

Unspecified error

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at DevHome.ExtensionLibrary.ViewModels.ExtensionLibraryViewModel.GetInstalledPackagesAndExtensionsAsync()
   at DevHome.ExtensionLibrary.ViewModels.ExtensionLibraryViewModel.<OnExtensionsChanged>b__17_0()
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass3_0.<<EnqueueAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at DevHome.ExtensionLibrary.ViewModels.ExtensionLibraryViewModel.OnExtensionsChanged(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i7-13700K
Physical Memory: 63.78GB (35.46GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.1800.621.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Canary))
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome.Canary_0.1801.621.0_x64__8wekyb3d8bbwe (Git (Canary))
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1300.621.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.24900.10.0_x64__cw5n1h2txyewy

### PR DESCRIPTION
**Pull request by krschau**
## Summary of the pull request
We saw a crash when the extensions list updated, even though we weren't on the Extensions page. When leaving the page, we should unsubscribe from extension events, since we don't want to respond to them if there's no UI to update. Also, move subscribing out of the constructor and into the Loaded event.

## PR checklist
- [ ] Closes #3859
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Review by AmelBawa-msft — APPROVED** [review]

File: tools/ExtensionLibrary/DevHome.ExtensionLibrary/ViewModels/ExtensionLibraryViewModel.cs [hunk 1]
```diff
@@ -69,6 +66,21 @@ public async Task LoadedAsync()
     {
         await GetInstalledPackagesAndExtensionsAsync();
         GetAvailablePackages();
+
+        if (_extensionService != null)
+        {
+            _extensionService.OnExtensionsChanged -= OnExtensionsChanged;
+            _extensionService.OnExtensionsChanged += OnExtensionsChanged;
```
Comment (guimafelipe) [inline tools/ExtensionLibrary/DevHome.ExtensionLibrary/ViewModels/ExtensionLibraryViewModel.cs:73]: Why do we do this at all? To trigger some kind of "on subscribe" event?

**Review by guimafelipe — APPROVED** [review]

File: tools/ExtensionLibrary/DevHome.ExtensionLibrary/ViewModels/ExtensionLibraryViewModel.cs (hunk 1 above)
Comment (krschau) [reply tools/ExtensionLibrary/DevHome.ExtensionLibrary/ViewModels/ExtensionLibraryViewModel.cs:73]: So we can update the page when the list changes -- for example, if something shows up in the list of extensions available in the store, and then you install it, you'll see the UI update it from being in that list to the list of installed extensions.
