### PR TITLE
Adding a delete confirmation popup for Environments; Fixing sync timer

### LINKED ISSUE #2509: Environments page operations need localized text code
### Steps to reproduce the bug

The underlying code for operations on VMs on the Environments page is hard coded.

### Actual result

The code should be using string helpers to make sure the text is getting translated.

### LINKED ISSUE #2662: Delete action for environments missing a secondary check
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Clicking 'Delete' immediately deletes an environment. 

### Expected result

The delete action should have a secondary check because its such a permanent action. 

### Actual result

Clicking 'Delete' immediately deletes an environment. 

Recommendation: Add an 'are you sure' confirmation before allowing them to delete an environment. 

### Included System Information

_No response_

### Included Extensions Information

_No response_

### LINKED ISSUE #2740: Environments sync information never updates
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

The environments page 'last synced' message always says Moments ago... even if it has been minutes since I synced. Either we are syncing too frequently, or we aren't updating the message accurately. 

### Expected result

_No response_

### Actual result

image

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by huzaifa-d**
## Summary of the pull request
Adds a delete confirmation popup for Environments
Adds localization for operations text
Adds back the sync timer code that was accidentally removed in #2432 

image

## PR checklist
- [x] Closes #2662 
- [x] Closes #2509 
- [x] Closes #2740 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs [hunk 1]
```diff
@@ -46,12 +51,22 @@ public partial class OperationsViewModel : IEquatable<OperationsViewModel>
 
     private Action? DevHomeAction { get; }
 
-    public OperationsViewModel(string name, string icon, Func<string, Task<ComputeSystemOperationResult>> command, ComputeSystemOperations computeSystemOperation)
+    private WinUIEx.WindowEx? _windowEx;
```
Comment (dhoehna) [inline tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:54]: The ViewModel can be made with DI.  That way windowEx does not need to be passed down the call chain.  

Does not need to be changed here because the constructor would need to change, and that would affect way too much code.

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs [hunk 2]
```diff
@@ -46,12 +51,22 @@ public partial class OperationsViewModel : IEquatable<OperationsViewModel>
...
+
+    private StringResource _stringResource = new("DevHome.Environments.pri", "DevHome.Environments/Resources");
+
+    public OperationsViewModel(
+        string name,
+        string icon,
+        Func<string, Task<ComputeSystemOperationResult>> command,
+        ComputeSystemOperations computeSystemOperation,
+        WinUIEx.WindowEx? windowEx = null)
```
Comment (dhoehna) [inline tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:63]: Is `windowEx` nullable because other locations don't pass it in?

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs [hunk 3]
```diff
@@ -98,6 +113,38 @@ public void InvokeAction()
         });
     }
 
+    [RelayCommand]
+    public void InvokeAction()
+    {
+        // Show confirmation popup in case of delete
+        if (Name == _stringResource.GetLocalized("Operations_Delete"))
```
Comment (krschau) [inline tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:120]: Better to use string.compare than ==, but in any case, comparing against a localized string doesn't seem great. Can you compare against the ComputeSystemOperation instead? The enum seems safer.

Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs]: Good point. Changed.

**Review by sshilov7 — APPROVED** [review]

File: tools/Environments/DevHome.Environments/Helpers/DataExtractor.cs [hunk 4]
```diff
@@ -33,7 +33,8 @@ public static List<OperationsViewModel> FillDotButtonOperations(ComputeSystem co
 
         if (supportedOperations.HasFlag(ComputeSystemOperations.Delete))
         {
-            operations.Add(new OperationsViewModel("Delete", "\uE74D", computeSystem.DeleteAsync, ComputeSystemOperations.Delete));
+            operations.Add(new OperationsViewModel(
+                _stringResource.GetLocalized("Operations_Delete"), "\uE74D", computeSystem.DeleteAsync, ComputeSystemOperations.Delete, windowEx));
```
Comment (krschau) [inline tools/Environments/DevHome.Environments/Helpers/DataExtractor.cs:37]: It looks like "Name" (the parameter you're passing "_stringResource.GetLocalized("Operations_Delete")" into) only gets used in GetHashCode(). If you're passing in ComputeSystemOperations.Delete, do you need to pass this in too, or will it always be "_stringResource.GetLocalized("Operations_Delete")" for that ComputeSystemOperations value?

Also, do you _want_ the Name in GetHashCode() to be localized?

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs (hunk 2 above)
Comment (krschau) [inline tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:63]: It seems like this is the version of the constructor that should be used if there could be a Delete action on it later. Is there some way we could enforce this in the future?

File: tools/Environments/DevHome.Environments/Helpers/DataExtractor.cs (hunk 4 above)
Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/Helpers/DataExtractor.cs:37]: It is actually used in the UI, through 
`<customControls:CardFlyout ItemsViewModels="{x:Bind DotOperations}"/>`

This change is for the UI only.

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs (hunk 2 above)
Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:63]: The confirmation popup code checks for null so I think that is enough. Would a separate constructor be better?

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs [hunk 5]
```diff
@@ -98,6 +113,38 @@ public void InvokeAction()
...
+        // Show confirmation popup in case of delete
+        if (ComputeSystemOperation == ComputeSystemOperations.Delete)
+        {
+            ContentDialog noWifiDialog = new ContentDialog
+            {
+                Title = _stringResource.GetLocalized("DeleteEnviroment_Title"),
+                Content = _stringResource.GetLocalized("DeleteEnviroment_Content"),
+                PrimaryButtonText = _stringResource.GetLocalized("DeleteEnviroment_ConfirmButton"),
+                SecondaryButtonText = _stringResource.GetLocalized("DeleteEnviroment_CancelButton"),
+                XamlRoot = _windowEx?.Content.XamlRoot,
```
Comment (dhoehna) [inline tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:128]: I believe this will crash if XamlRoot is null.

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs (hunk 2 above)
Comment (krschau) [reply tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:63]: I meant more like, can they use a different constructor, do the delete action, and not see the popup? The null check will prevent a crash, but could the user still find themselves in a situation where they're not warned?

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs (hunk 5 above)
Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:128]: It won't run if it is. See the following lines.

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs [hunk 6]
```diff
@@ -78,9 +93,9 @@ public OperationsViewModel(string name, string icon, Action command)
         DevHomeAction = command;
     }
 
-    [RelayCommand]
-    public void InvokeAction()
+    private void RunAction()
     {
+        // We'll need to disable the card UI while the operation is in progress and handle failures.
```
[the remark this answers is not in the document]
Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs]: Not my comment, but good point. I changed it.

**Review by kanismohammed — APPROVED** [review]

File: tools/Environments/DevHome.Environments/Helpers/DataExtractor.cs (hunk 4 above)
Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/Helpers/DataExtractor.cs:37]: How will I get the value of WindowEx that I am passing?

File: tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs (hunk 2 above)
Comment (huzaifa-d) [reply tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs:63]: I don't think so, since this is where the action is called from. And all future changes will happen here, and should not miss code in the relevant function.
