### PR TITLE
Various fixes

### LINKED ISSUE #1239: PluginSDK build.ps1 overrides configuration for root build.ps1
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Run Build.ps1 from root with -Configuration "debug"

### Expected result

DevHome gets built as debug

### Actual result

DevHome gets built as release

### Included System Information

_No response_

### Included Extensions Information

_No response_

### LINKED ISSUE #1240: Canary build of Dev Home auto-install the Preview version of GitHub Extension
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

Install and run the Canary build of Dev Home.

### Expected result

Canary build of GitHub Extension is installed.

### Actual result

Preview build of GitHub Extension is installed.

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by EricJohnson327**
## Summary of the pull request
1) Dev Home (Canary) will now auto install GitHub Extension (Canary) instead of Preview.
2) Dev Home (Dev) will not install anything.
3) Building PluginSDK will no longer force Dev Home to build as release.

## PR checklist
- [ ] Closes #1239
- [ ] Closes #1240 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: src/ViewModels/InitializationViewModel.cs [hunk 1]
```diff
@@ -13,9 +13,17 @@
...
-{
+{
+#if CANARY_BUILD
+    private const string GitHubExtensionStorePackageId = "9N806ZKPW85R";
+    private const string GitHubExtensionPackageFamilyName = "Microsoft.Windows.DevHomeGitHubExtension.Canary_8wekyb3d8bbwe";
+#elif STABLE_BUILD
     private const string GitHubExtensionStorePackageId = "9NZCC27PR6N6";
     private const string GitHubExtensionPackageFamilyName = "Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe";
+#else
+    private const string GitHubExtensionStorePackageId = "";
```
Comment (krschau) [inline src/ViewModels/InitializationViewModel.cs:24]: What happens in StartAppInstallAsync() when this is empty? Maybe a comment would be helpful.

**Comment by krschau** [comment]
Please give the PR a better name before merging.

File: src/ViewModels/InitializationViewModel.cs [hunk 2]
```diff
@@ -13,9 +13,17 @@
 
 namespace DevHome.ViewModels;
 public class InitializationViewModel : ObservableObject
-{
+{
+#if CANARY_BUILD
```
Comment (AmelBawa-msft) [inline src/ViewModels/InitializationViewModel.cs:17]: Not in this PR. Today we have a single `appsettings.json` we use for configuring Dev Home. We can also create `appsettings.Production.json`, `appsettings.Developement.json` and `appsettings.Canary.json` and store the corresponding PID and PFM in them. This will allow us to mock these values in unit test and decouple the compiler logic from the code. Resolving.

File: src/ViewModels/InitializationViewModel.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (EricJohnson327) [reply src/ViewModels/InitializationViewModel.cs:24]: Added!

Comment (EricJohnson327) [reply src/ViewModels/InitializationViewModel.cs:24]: Honestly, nothing really happens.  The API fires an exception which we catch and log, but to the user the initialization page just finishes immediately and Dev Home works as expected.  Still... added a null check to be a bit cleaner :)

**Review by AmelBawa-msft — APPROVED** [review]

**Review by krschau — APPROVED** [review]
