### PR TITLE
Fix VM state update after executing an operation.

### LINKED ISSUE #2861: Environment states are not updated when an operation is executed (Start, Stop etc)
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

1. Go to Environment page
2. Click on Start on any environment

### Expected result

Status should be starting ang then started

### Actual result

Indefinite progress bar until the sync button is pressed

### Included System Information

_No response_

### Included Extensions Information

_No response_

### PR DESCRIPTION
**Pull request by sshilov7**
## Summary of the pull request
VM status update regressed on the Landing page after #2824
Adding VM status refresh to get new values from the VM instead of cached ones and correct StateChanged event handling.

## References and relevant issues
[Environment states are not updated when an operation is executed (Start, Stop etc)](#2861)

## PR checklist
- [ ] Closes #2861 
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

File: tools/SetupFlow/DevHome.SetupFlow/ViewModels/Environments/ComputeSystemCardViewModel.cs [hunk 1]
```diff
@@ -1,134 +1,134 @@
...
-    }
-
-    public ComputeSystemCardViewModel(ComputeSystemCache computeSystem, IComputeSystemManager manager, WindowEx windowEx)
-    {
-        _windowEx = windowEx;
-        _computeSystemManager = manager;
-        ComputeSystemTitle = computeSystem.DisplayName.Value;
-        ComputeSystem = computeSystem;
-        ComputeSystem.StateChanged += _computeSystemManager.OnComputeSystemStateChanged;
+
```
Comment (sshilov7) [inline tools/SetupFlow/DevHome.SetupFlow/ViewModels/Environments/ComputeSystemCardViewModel.cs:20]: CR/LF

**Review by bbonaby — APPROVED** [review]

**Review by kanismohammed — APPROVED** [review]
